nn_type: FCx1
num_epochs: 50
learning_rate: 0.0001
continue_train: False
pth_path: "weights_log/NN_FCx1_device=cuda-epoch=20-acc=48.9600.pth"
pth_test: "weights/NN_FCx1_time=20220502-172008_device=cuda_epoch=40_acc=51.3200.pth"